// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVOoEpi1EahG8FSPemnA70fOE5epG_70w',
    appId: '1:321319695378:web:551ec941ba7cbf66c654cb',
    messagingSenderId: '321319695378',
    projectId: 'new1-8b4b2',
    authDomain: 'new1-8b4b2.firebaseapp.com',
    storageBucket: 'new1-8b4b2.appspot.com',
    measurementId: 'G-YGLSXNEY0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9tE5Chq28Po-cOCs_ErRlEknkV7eVkv8',
    appId: '1:321319695378:android:4081a79ccbc932fac654cb',
    messagingSenderId: '321319695378',
    projectId: 'new1-8b4b2',
    storageBucket: 'new1-8b4b2.appspot.com',
  );
}
